### ISSUE TITLE
这个efi是完全版么

### ISSUE THREAD

**Issue by 317673767** [zhangcheng142/m710q-qnct#1]
我也是m710q+qnct，黑果小兵镜像+efi替换，直接显示config损坏 代码都没跑起来，参照你的设置，起个新的0.64的config，卡代码，没看到磁盘管理
![IMG_20210130_193652](https://user-images.githubusercontent.com/77151591/106357745-9acee480-62cd-11eb-9208-b829df59e757.jpg)

**Comment by zhangcheng142** [comment]
EFI是完整的，我本地运行完成正常，我后来又更新了intel无线网卡的驱动和图形的UI部分，都还没提交。
你直接用我这个都不能启动吗？如果不行，怀疑可能和魔改的BIOS或者QNCT的体质有关。

**Comment by 317673767** [comment]
能分享一份bios，bios设置截图，新的efi么，我也怀疑是bois的问题，换个bios试一试

**Comment by zhangcheng142** [comment]
add wx: zhangcheng142
